### ISSUE TITLE
Support `import.meta.hot`

### ISSUE THREAD

**Issue by mpeyper** [OpenSourceRaidGuild/babel-vite#3]
### Describe the feature you'd like:

As part of looking at #1, I discovered the Vite has another piece of `import.meta` functionality that we aren't supporting yet: `import.meta.hot`.

[Link to docs.](https://vitejs.dev/guide/api-hmr.html)

### Suggested implementation:

I think we would be pretty safe to simply remove any references to it as in most cases we are transforming for test code where HMR is not applicable (AFAIK) and/or environments where HMR is not available or available through different APIs.

As per the other transforms, it should be able to be disabled from the preset so other babel plugins could handle it in specialised ways or it can be left in if the target environment supports it.

### Describe alternatives you've considered:

None.

**Comment by neoighodaro** [comment]
Hello, would this be possible?

**Comment by mpeyper** [comment]
Hi @neoighodaro, sorry for the delayed response.

I haven't looked into it at all since raising it, but as usual PRs are always welcome.  Would you be interested in adding this feature?
