### ISSUE TITLE
Unable to get this plugin working with ts-jest

### ISSUE THREAD

**Issue by ghost** [OpenSourceRaidGuild/babel-vite#7]
### What is your question:

I'm in the process of porting a Typescript create-react-app project to vite. In this project we have a `src` folder containing the app's code and a `test` folder to hold the jest tests that are transformed using `ts-jest`.

The issue is that the files in `src` are using `import.meta` and I am attempting to use `babel-plugin-transform-vite-meta-env` to convert them for the unit tests, however I have not had any luck getting it to work. It seems as though something is wrong with my setup as it doesn't seem like jest is recognizing that it needs to run the transform.

My jest config looks like this:
```js
module.exports = {
    preset: "ts-jest",
    testEnvironment: "node",
    moduleDirectories: [
        "node_modules",
        "src",
        "test"
    ],

    globals: {
        "ts-jest": {
            tsconfig: "test/tsconfig.json",
            babelConfig: {
                plugins: ["babel-plugin-transform-vite-meta-env"]
            }
        }
    }
};
```

Relevant dependencies:
```
"dependencies": {
    "@babel/core": "^7.16.0",
    "@types/jest": "^27.0.2",
    "@types/node": "^12.0.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^27.3.1",
    "babel-plugin-transform-vite-meta-env": "^1.0.3",
    "jest": "^27.3.1",
    "ts-jest": "^27.0.7",
    "typescript": "4.4.4",
}
```

Running jest yields the error `error TS2339: Property 'env' does not exist on type 'ImportMeta'.` on any files in `src` that use `import.meta`.

Note that the only files I need transformed as those in the `src` directory and that despite this being a React project I do not use any .tsx files for testing.

**Comment by mpeyper** [comment]
Sorry for the delayed response.

This appears to be a TS error and not related to the babel transformation we are providing.  You likely need to [extend the `ImportMeta` interface with the required keys](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#support-for-importmeta) for the TS compilation to also work (I'm not sure what `ts-jest` is exactly doing behind the scenes).

If you're interested, [here is an example](https://github.com/OpenSourceRaidGuild/atom-pwa) or a project using TS and jest and this plugin (but not `ts-jest` if that helps at all.

If there is some way we can support this better, please let us know, but for now I will close this as I don't think there is anything we can do to implicitly inform TS about the the type of our transformation.
